# Generated by Django 2.2.3 on 2019-08-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topstoryinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.CharField(max_length=10, unique=True)),
                ('username', models.CharField(blank=True, max_length=45, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=2000, null=True)),
                ('score', models.CharField(blank=True, max_length=10, null=True)),
                ('story_desc', models.CharField(blank=True, max_length=245, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('time', models.CharField(blank=True, max_length=10, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=10, null=True)),
                ('istrending', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'topstoryinfo',
                'managed': False,
            },
        ),
    ]
